EXECUTION:
  DATAREADER:
    CRAWLER_ARGS: 
      data_folder: Data
      include: ["cmu_miscov19"] # Adjust this to specific EFND dataset
  EPOCHS: 10
  FP16: False
  MODEL_SERVING: False
  OPTIMIZER_BUILDER: ClassificationOptimizer
  SKIPEVAL: False
  TEST_FREQUENCY: 1
  TRAINER: BaseTrainer
  TRAINER_ARGS: 
    accumulation_steps: 8


SAVE:
  MODEL_VERSION: 1
  MODEL_CORE_NAME: fnc-expert-efnd
  MODEL_BACKBONE: albert
  MODEL_QUALIFIER: cmu_miscov19
  DRIVE_BACKUP: True
  SAVE_FREQUENCY: 3 # Epoch
  CHECKPOINT_DIRECTORY: "./drive/MyDrive/Projects/FNC/Models/"