
DEPLOYMENT:
  OUTPUT_ARGS:
    neighbor_output: neighbor
    unfiltered_output: unfiltered
    basename: tweets-2020-01-22
  DEPLOY: BaseDeploy
  DATAREADER:
    CRAWLER_ARGS: 
      azstorage: ednadatasets
      azcontainer: edna-covid-raw
      azfile: tweets-2020-01-22.json.gz
    DATAREADER: AlbertReader
    DATASET_ARGS:
      classificationclass: ['fnews']
      maxlen: 512
      shardcache: True
      shardsize: 20000
      shard_replace: False
      shardpath: datashard-artifacts
      shardname: fnc-unmasked-shard
      mlm_probability: 0.15
      masking: False
      shuffle: False
      data_shuffle: False
      keyword_mask: False
    GENERATOR_ARGS: 
      tokenizer: HFAutoTokenizer
      from_pretrained: albert-base-v2
  FP16: False
  EPOCHS: 1
  PLUGIN:
    HOOKS: activated
    RESET: False

MODEL_PLUGIN:
  - PLUGIN: FastKMP
    PLUGIN_NAME: FastKMP-l2
    PLUGIN_KWARGS:
      proxies: 20
      dimensions: 768
      dist: euclidean
      iterations: 30
      batch_size: 256
      alpha: 0.5