
DEPLOYMENT:
  OUTPUT_ARGS:
    oracle_output: oracle
    extended_output: extended
    basename: tweets-2020-01-22
  DEPLOY: BaseDeploy
  FP16: False
  EPOCHS: 1
  PLUGIN:
    HOOKS: activated
    RESET: False

DATAREADER:
  CRAWLER_ARGS: 
    azstorage: ednadatasets
    azcontainer: edna-covid-raw
    azfile: tweets-2020-01-22.json.gz
  DATAREADER: AlbertReader
  DATASET_ARGS:
    classificationclass: ['fnews']
    maxlen: 512
    shardcache: True
    shardsize: 20000
    shard_replace: False
    shardpath: datashard-artifacts
    shardname: fnc-extended-unmasked-shard
    mlm_probability: 0.15
    masking: False
    shuffle: False
    data_shuffle: False
    keyword_mask: False
  GENERATOR_ARGS: 
    tokenizer: HFAutoTokenizer
    from_pretrained: albert-base-v2


MODEL_PLUGIN:
  - PLUGIN: FastKMP
    PLUGIN_NAME: FastKMP-l2
    PLUGIN_KWARGS:
      proxies: 20
      dimensions: 768
      dist: euclidean
      iterations: 30
      batch_size: 256
      alpha: 0.5