EXECUTION:
  MODEL_SERVING: None
  EPOCHS: 120
  TEST_FREQUENCY: 5
  OPTIMIZER_BUILDER: VAEGANOptimizerBuilder
  MODEL_BUILDER: vaegan_model_builder 
  TRAINER: VAEGANTrainer
  DATASET_PRELOAD: "MNIST"
  DATASET_PRELOAD_CLASS: [0]


SAVE:
  MODEL_VERSION: 1
  MODEL_CORE_NAME: "ablation_reid"
  MODEL_BACKBONE: "res50"
  MODEL_QUALIFIER: "all"
  DRIVE_BACKUP: True
  SAVE_FREQUENCY: 5 # Epoch

DATASET:
  ROOT_DATA_FOLDER: "VeRi"
  TRAIN_FOLDER: "image_train"
  TEST_FOLDER: "image_test"
  QUERY_FOLDER: "image_query"
  SHAPE: [32,32]

TRANSFORMATION:
  NORMALIZATION_MEAN: 0.5
  NORMALIZATION_STD: 0.5
  NORMALIZATION_SCALE: 255
  H_FLIP: 0.5
  T_CROP: True
  RANDOM_ERASE: True
  RANDOM_ERASE_VALUE: 0.5
  CHANNELS: 3
  BATCH_SIZE: 36
  INSTANCES: 6
  WORKERS: 8

MODEL:
  LATENT_DIMENSIONS: 128
  MODEL_KWARGS: '{}'

LOSS:
  LOSSES: ['SoftmaxLogitsLoss', 'TripletLoss']
  LOSS_KWARGS: [{}, {'margin':0.3, 'mine':'hard'}]
  LOSS_LAMBDAS: [1.0, 1.0]

OPTIMIZER:
  OPTIMIZER_NAME: "Adam"
  OPTIMIZER_KWARGS: '{"betas:[0.5, 0.999]"}'
  BASE_LR: 0.0001
  LR_BIAS_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_BIAS_FACTOR: 0.0005
  FP16: True

SCHEDULER:
  ENCODER_LR_SCHEDULER: 'StepLR'
  ENCODER_LR_KWARGS: '{"step_size":30, "gamma":0.25}'

LOGGING:
  STEP_VERBOSE: 100 # Batch