DATASET:
  ROOT_DATA_FOLDER: "VeRi"
  TRAIN_FOLDER: "image_train"
  TEST_FOLDER: "image_test"
  QUERY_FOLDER: "image_query"
  SHAPE: [208,208]

TRANSFORMATION:
  NORMALIZATION_MEAN: 0.5
  NORMALIZATION_STD: 0.5
  NORMALIZATION_SCALE: 255
  H_FLIP: 0.5
  T_CROP: True
  RANDOM_ERASE: True
  RANDOM_ERASE_VALUE: 0.5
  CHANNELS: 3
  BATCH_SIZE: 36
  INSTANCES: 6
  WORKERS: 8

MODEL:
  MODEL_BASE: 'resnet50'
  MODEL_ARCH: 'Resnet'
  MODEL_WEIGHTS: True
  MODEL_ATTENTION: ''
  EMB_DIM: 2048
  MODEL_NORMALIZATION: 'bn'
  MODEL_KWARGS: '{}'

SAVE:
  SAVE_FREQUENCY: 5 # Epoch
  MODEL_VERSION: 2
  MODEL_CORE_NAME: "torch_reid"
  MODEL_BACKBONE: "res50"
  MODEL_QUALIFIER: "all"
  DRIVE_BACKUP: True

EXECUTION:
  MODE: "TRAIN"
  MODEL_SERVING: None
  EPOCHS: 260
  TEST_FREQUENCY: 5

LOSS:
  LOSSES: ['SoftmaxLogitsLoss', 'TripletLoss']
  LOSS_KWARGS: [{}, {'margin':0.3, 'mine':'hard'}]
  LOSS_LAMBDAS: [1.0, 1.0]

OPTIMIZER:
  OPTIMIZER_NAME: "Adam"
  OPTIMIZER_KWARGS: '{}'
  BASE_LR: 0.0001
  LR_BIAS_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_BIAS_FACTOR: 0.0005
  FP16: True

SCHEDULER:
  LR_SCHEDULER: 'FineGrainedSteppedLR'
  LR_KWARGS: '{"lr_ops":[[2,"+",2e-5], [4,"+",2e-5], [6,"+",2e-5], [8,"+",2e-5], [10,"+",2e-5], [20,"*",0.9], [40,"+",0.8], [60,"+",0.7], [80,"+",0.7], [100,"+",0.6], [120,"+",0.5]]}'

LOGGING:
  STEP_VERBOSE: 100 # Batch