EXECUTION:
  MODEL_SERVING: None
  EPOCHS: 25
  TEST_FREQUENCY: 1
  CRAWLER: VehicleIDDataCrawler
  TRAINER: VehicleIDTrainer

SAVE:
  MODEL_VERSION: 7
  MODEL_CORE_NAME: "vehicleid_final"
  MODEL_BACKBONE: "res18"
  MODEL_QUALIFIER: "all"
  DRIVE_BACKUP: True
  SAVE_FREQUENCY: 1 # Epoch

DATASET:
  ROOT_DATA_FOLDER: "Data/VehicleID"
  TRAIN_FOLDER: "image"
  TEST_FOLDER: ""
  QUERY_FOLDER: ""
  SHAPE: [384,384]

TRANSFORMATION:
  NORMALIZATION_MEAN: 0.5
  NORMALIZATION_STD: 0.5
  NORMALIZATION_SCALE: 255
  H_FLIP: 0
  T_CROP: False
  RANDOM_ERASE: False
  RANDOM_ERASE_VALUE: 0.5
  CHANNELS: 3
  BATCH_SIZE: 72
  INSTANCES: 18
  WORKERS: 8

MODEL:
  MODEL_BASE: 'resnet18'
  MODEL_ARCH: 'Resnet'
  EMB_DIM: 512
  SOFTMAX: 
  MODEL_NORMALIZATION: 'ln'
  MODEL_KWARGS: 
    part_attention: true
    ia_attention: true
LOSS:
  LOSSES: ['MarginLoss', 'CenterLoss']
  LOSS_KWARGS: [{'margin':0.3, 'mine':'hard'}, {'num_classes':13164, 'feat_dim':512}]
  LOSS_LAMBDAS: [1.0, 0.0005]

OPTIMIZER:
  OPTIMIZER_NAME: "AdamW"
  OPTIMIZER_KWARGS: '{}'
  BASE_LR: 0.0001
  LR_BIAS_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_BIAS_FACTOR: 0.0005
  FP16: True

SCHEDULER:
  LR_SCHEDULER: 'StepLR'
  LR_KWARGS: '{"step_size":10, "gamma":0.6}'

LOGGING:
  STEP_VERBOSE: 200 # Batch