EXECUTION:
  MODEL_SERVING: None
  EPOCHS: 121
  TEST_FREQUENCY: 5
  OPTIMIZER_BUILDER: VAEGANOptimizerBuilder
  MODEL_BUILDER: vaegan_model_builder 
  TRAINER: VAEGANTrainer
  DATASET_PRELOAD: "CIFAR10"
  DATASET_PRELOAD_CLASS: [0,1,2]
  DATASET_TEST_PRELOAD_CLASS: [3,4,5,6,7,8,9]


SAVE:
  MODEL_VERSION: 4
  MODEL_CORE_NAME: "vaegan_cifar"
  MODEL_BACKBONE: "vaegan"
  MODEL_QUALIFIER: "cifar10"
  DRIVE_BACKUP: True
  SAVE_FREQUENCY: 5 # Epoch

DATASET:
  ROOT_DATA_FOLDER: "CIFAR10" # Not used for build-in data loader
  TRAIN_FOLDER: ""
  TEST_FOLDER: ""
  QUERY_FOLDER: ""
  SHAPE: [32,32]

TRANSFORMATION:
  NORMALIZATION_MEAN: 0.5
  NORMALIZATION_STD: 0.5
  NORMALIZATION_SCALE: 255.0
  H_FLIP: 0
  T_CROP: False
  RANDOM_ERASE: False
  RANDOM_ERASE_VALUE: 0.5
  CHANNELS: 3
  BATCH_SIZE: 64
  WORKERS: 1

MODEL:
  BASE: 32
  ARCH: "VAEGAN"
  LATENT_DIMENSIONS: 256
  MODEL_KWARGS: '{"channels":3}'

OPTIMIZER:
  OPTIMIZER_NAME: "Adam"
  OPTIMIZER_KWARGS: '{"betas":[0.5, 0.999]}'
  BASE_LR: 0.002
  LR_BIAS_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_BIAS_FACTOR: 0.0005
  FP16: True

SCHEDULER:
  LR_SCHEDULER: 'StepLR'
  LR_KWARGS: '{"step_size":30, "gamma":0.25}'
  

LOGGING:
  STEP_VERBOSE: 25 # Batch