EXECUTION:
  MODEL_SERVING: None
  EPOCHS: 120
  TEST_FREQUENCY: 5
  CRAWLER: VRICDataCrawler

SAVE:
  MODEL_VERSION: 1
  MODEL_CORE_NAME: "debugging"
  MODEL_BACKBONE: "res18"
  MODEL_QUALIFIER: "all"
  DRIVE_BACKUP: False
  SAVE_FREQUENCY: 5 # Epoch

DATASET:
  ROOT_DATA_FOLDER: "Data/VRIC"
  TRAIN_FOLDER: "train_images"
  TEST_FOLDER: "gallery_images"
  QUERY_FOLDER: "probe_images"
  SHAPE: [104,104]

TRANSFORMATION:
  NORMALIZATION_MEAN: 0.5
  NORMALIZATION_STD: 0.5
  NORMALIZATION_SCALE: 255
  H_FLIP: 0.5
  T_CROP: True
  RANDOM_ERASE: True
  RANDOM_ERASE_VALUE: 0.5
  CHANNELS: 3
  BATCH_SIZE: 12
  INSTANCES: 6
  WORKERS: 1

MODEL:
  MODEL_BASE: 'resnet18'
  MODEL_ARCH: 'Resnet'
  EMB_DIM: 512
  MODEL_NORMALIZATION: ''
  MODEL_KWARGS: '{}'

LOSS:
  LOSSES: ['SoftmaxLogitsLoss', 'TripletLoss']
  LOSS_KWARGS: [{}, {'margin':0.3, 'mine':'hard'}]
  LOSS_LAMBDAS: [1.0, 1.0]

OPTIMIZER:
  OPTIMIZER_NAME: "Adam"
  OPTIMIZER_KWARGS: '{}'
  BASE_LR: 0.001
  LR_BIAS_FACTOR: 1.0
  WEIGHT_DECAY: 0.0005
  WEIGHT_BIAS_FACTOR: 0.0005
  FP16: True

SCHEDULER:
  LR_SCHEDULER: 'ExponentialLR'
  LR_KWARGS: '{"gamma":0.94}'

LOGGING:
  STEP_VERBOSE: 100 # Batch